import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Layout } from "components";

const Home: NextPage = () => {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="w-full px-4">
				<section className="max-w-7xl mx-auto py-16">
					<h1 className="text-9xl font-bold mb-8">
						Welcome to <br />
						PScale Auth
					</h1>
					<Link href={"/profile"}>
						<button className="bg-blue-500 border border-blue-500 hover:bg-blue-600 hover:border-blue-600 px-4 py-2 rounded-md text-white font-bold tracking-wide text-sm uppercase">
							Go to profile page
						</button>
					</Link>
				</section>
			</main>
		</Layout>
	);
};

export default Home;
