import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
	const { data: session } = useSession();

	return (
		<div className="min-h-screen">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="sticky top-0 w-full px-4">
				<nav className="flex items-center justify-between max-w-7xl mx-auto py-2">
					<span>
						<Link href={"/"}>PScale Auth</Link>
					</span>
					{session ? (
						<span>{session.user?.email}</span>
					) : (
						<ul className="flex space-x-4">
							<li>
								<Link href={"/signin"}>Sign in</Link>
							</li>
							<li>
								<Link href={"/signup"}>Sign up</Link>
							</li>
						</ul>
					)}
				</nav>
			</div>
			<main className="w-full px-4">
				<section className="max-w-7xl mx-auto py-16">
					<h1 className="text-9xl font-bold mb-8">
						Welcome to <br />
						PScale Auth
					</h1>
					<Link href={"/profile"}>
						<button className="bg-blue-500 border border-blue-500 hover:bg-blue-600 hover:border-blue-600 px-4 py-2 rounded-md text-white font-bold tracking-wide text-sm uppercase">
							Go to profile page
						</button>
					</Link>
				</section>
			</main>
		</div>
	);
};

export default Home;
